//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PublisherName { get; set; }
        public string Age { get; set; }
        public System.DateTime Date { get; set; }
        public string Page { get; set; }
        public string BookType { get; set; }
    }
}
